---
abstract: "just print modules' C<$VERSION> (and some other stuff)"
author:
  - 'Alexey Surikov <ksuri@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: App::Mver
name: App-Mver
no_index:
  directory:
    - inc
recommends:
  JSON::Any: 0
  LWP::Simple: 0
  Module::CoreList: 0
requires:
  ExtUtils::MakeMaker: 0
  Pod::Parser: 0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.07
